title: Emarsys Design System Roadmap

baseurl: "/emarsys-design-system-roadmap"

permalink: /:title/

future: true

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

timezone: Europe/Budapest

exclude:
  - docker-compose.xml
  - Makefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
