title: Emarsys Design System Roadmap

footer-links:
  rss:

disqus:

google_analytics:

url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/emarsys-design-system-roadmap"

permalink: /:title/

future: true

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Timezone
timezone: Europe/Budapest

# Exclude these files from your production _site
exclude:
  - docker-compose.xml
  - Makefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
